name: Playwright Tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run tests
      run: |
        docker build -t playwright-tests .
        docker run --rm -v $PWD/test-results:/app/test-results playwright-tests
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/